version: '3.8'

services:
  db:
    image: postgres:15
    container_name: travel_booking_db
    restart: always
    environment:
      POSTGRES_DB: travel_booking_db
      POSTGRES_USER: travelbooking
      POSTGRES_PASSWORD: travelbooking123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - travel_network

  web:
    build: .
    container_name: travel_booking_web
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_NAME=travel_booking_db
      - DB_USER=travelbooking
      - DB_PASSWORD=travelbooking123
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
    networks:
      - travel_network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  travel_network:
    driver: bridge
